### ISSUE TITLE
Appears to be sending malformed APRS packets

### ISSUE THREAD

**Issue by mytechguyri** [g4klx/APRSGateway#11]
Looking at the raw packet data received from my Pistar instance, I'm seeing the following:

APDG03,TCPIP*,qAC,WA1OKB-RS:!4141.17NW07123.96WW/A=00006670cm MMDVM Voice 442.55000MHz +5.0000MHz; APRS for DMRGateway
  
Specifically this section:  4141.17N**W**07123.96W**W**    The W character between latitude and longitude is supposed to indicate the Symbol Table Identifier (so W is an illegal character there it should be either / indicating the Primary symbol table or \ indicating the alternate symbol table), and the character at the end (the third W) is the Symbol Code from that table.  In this case, W which is erroneously indicating National Weather Service station. (Please see Appendix 2 at http://www.aprs.org/doc/APRS101.PDF for the symbol tables)

It would be more appropriate to use the antenna tower symbol, i.e. 4141.17N/07123.96Wr
or perhaps 4141.17N\07123.96Wi for a low power hotspot
Or even better.  Allow the end user to specify the symbole table (either / or \ ) and the symbol in the config file.... but regardless National Weather Service Site is definitely incorrect.

**Comment by W0CHP** [comment]
@g4klx , you can close this, as this is *not* an upstream issue. @mytechguyri open this issue with me at https://repo.w0chp.net/Chipster/WPSD_CustomBinaries-Source/issues since you're using `W0CHP-PiStar-Dash` which uses custom-compiled APRSGW binaries.
